language: node_js
node_js:
  - lts/*
before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
install:
  - yarn install
script:
npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: example/react-app-demo/build
  github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: master